#Token para o email user@mail.com e a senha 123@123, valido por um dia, gere um novo token em ./http/user.http | Precisa do Rest Client instalado no VScode
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc3NDcwOTIxNSwiZXhwIjoxNzc0Nzk1NjE1fQ.BLfqTxjo-fiXQxG3pmQxw0EwO-fjKSV1bxxmR5i-Ofs

###

GET http://localhost:3000/v1/category/3

###

POST http://localhost:3000/v1/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "shoes",
  "slug": "shoes",
  "use_in_menu": true
}  
###

PUT http://localhost:3000/v1/category/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "nao sei",
  "slug": "cavalo",
  "use_in_menu": false
}  


###

DELETE http://localhost:3000/v1/category/10
Authorization: Bearer {{token}}