#Token para o email user@mail.com e a senha 123@123, valido por um dia, gere um novo token em ./http/user.http | Precisa do Rest Client instalado no VScode
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJ1c2VyQG1haWwuY29tIiwiaWF0IjoxNzc0NTQyNDAxLCJleHAiOjE3NzQ2Mjg4MDF9.kE8FbLRsmUFGGEjANubRJdCjZLlHTh_S9DNIVz5kPsM

GET http://localhost:3000/v1/product/search?limit=-1&match=jeans&option[14]=40,42

###

GET http://localhost:3000/v1/product/32

###

POST http://localhost:3000/v1/product
Content-Type: application/json
Authorization: Bearer {{token}}

  {
    "enabled": true,
    "name": "Produto 01",
    "slug": "produto-01",
    "stock": 10,
    "description": "Descrição do produto 01",
    "price": 119.90,
    "price_with_discount": 99.90,
    "category_ids": [7, 3,2],
    "images": [ 
      {
        "type": "image/png",
        "content": "base64 da imagem 1" 
      },
      {
        "type": "image/png",
        "content": "base64 da imagem 2" 
      },
      {
        "type": "image/jpg",
        "content": "base64 da imagem 3" 
      }
    ],
    "options": [
      {
        "title": "Cor",
        "shape": "square",
        "radius": "4px",
        "type": "text",
        "values": ["PP", "GG", "M"]
      },
      {
        "title": "Tamanho",
        "shape": "circle",
        "type": "color",
        "values": ["#000", "#333"]
      }
    ]
  }

###

PUT http://localhost:3000/v1/product/6
Content-Type: application/json
Authorization: Bearer {{token}}

  {
    "enabled": true,
    "name": "Produto 01 atualizado",
    "slug": "produto-01-atualizado",
    "stock": 20,
    "description": "Descrição do produto 01 atualizado",
    "price": 49.9,
    "price_with_discount": 0,
    "category_ids": [1, 2, 6],
    "images": [ 
      {
        "type": "image/png",
        "content": "base64 da imagem 1" 
      },
      {
        "content": "/uploads/imagemdetest5"
      },
      {
        "id": 7,
        "content": "imagem atualizada" 
      }
    ],
    "options": [
      {
        "id": 4,
        "radius": "10px",
        "values": ["42/43", "44/45"]
      },
      {
        "title": "Tipo",
        "shape": "square",
        "type": "text",
        "values": ["100% algodão", "65% algodão"]
      }
    ]
  }

###

DELETE http://localhost:3000/v1/product/6
Authorization: Bearer {{token}}